<?php
// Project/contract history exported from Acumatica. Regenerated from the source
// spreadsheet - see _extract/projects-data.csv for the raw export.
$GLOBALS['PROJECT_RECORDS'] = [
    ['id' => '18-9999', 'name' => 'SSRM Lawsuit / MFF Slab Issues', 'type' => 'OH / Internal'],
    ['id' => '20-3010', 'name' => 'Omaha Nation Career Academy', 'type' => 'Schools/Colleges'],
    ['id' => '20-3011', 'name' => 'ONCA CMAR Paid Changes', 'type' => 'Schools/Colleges'],
    ['id' => '20-6051', 'name' => 'Wholestone Pork-Snap Chill', 'type' => 'Industrial'],
    ['id' => '21-1060', 'name' => 'FIMCO Silo Pad', 'type' => 'Industrial'],
    ['id' => '21-4010', 'name' => 'Tyson WWTP Storm Lake', 'type' => 'WWTP'],
    ['id' => '21-6030', 'name' => 'Smithfield WW Pretreatment Sioux City', 'type' => 'WWTP'],
    ['id' => '21-6040', 'name' => 'SRK Dunes Strip Mall', 'type' => 'Retail'],
    ['id' => '21-6050', 'name' => 'Fairfield Inn Yankton', 'type' => 'Hotel'],
    ['id' => '21-6051', 'name' => 'Fairfield Inn Yankton Transformer Pad', 'type' => 'Hotel'],
    ['id' => '22-0010', 'name' => 'Bertrand EWAC 2022', 'type' => 'EWAC'],
    ['id' => '22-0020', 'name' => 'Anderson EWAC 2022', 'type' => 'EWAC'],
    ['id' => '22-0030', 'name' => 'Hodgson EWAC 2022', 'type' => 'EWAC'],
    ['id' => '22-0090', 'name' => 'RJ Tide 2022 Capital Improvements', 'type' => 'OH / Internal'],
    ['id' => '22-1000', 'name' => 'Diocese of Sioux City Sidewalks', 'type' => 'Flatwork'],
    ['id' => '22-1010', 'name' => 'Good Samaritan Stair Repairs-1318 S Alice', 'type' => 'Flatwork'],
    ['id' => '22-1020', 'name' => 'Dunes Strip Mall Transformer Pad', 'type' => 'Retail'],
    ['id' => '22-1030', 'name' => 'NSC Lift Station Generator Pads', 'type' => 'Industrial'],
    ['id' => '22-1040', 'name' => 'FIMCO 2022 Opus T&M', 'type' => 'Warehouse'],
    ['id' => '22-1050', 'name' => 'Gelita HCL Storage', 'type' => 'Industrial'],
    ['id' => '22-1060', 'name' => 'SC Water Treatment Pole Replacement', 'type' => 'Industrial'],
    ['id' => '22-1070', 'name' => 'Mater Dei Misc. Concrete 2022', 'type' => 'Flatwork'],
    ['id' => '22-1080', 'name' => 'Michael Foods Salt Tank Foundation', 'type' => 'Industrial'],
    ['id' => '22-1090', 'name' => 'Bomgaars Parking Lot Repairs', 'type' => 'Flatwork'],
    ['id' => '22-1100', 'name' => 'Kuchel Roofing Flatwork', 'type' => 'Flatwork'],
    ['id' => '22-1110', 'name' => 'Sunnybrook Church Paving', 'type' => 'Flatwork'],
    ['id' => '22-1120', 'name' => 'Lewis & Clark Ballpark Sidewalk Replacement', 'type' => 'Flatwork'],
    ['id' => '22-1130', 'name' => 'City of North Sioux City Water Main Repair', 'type' => 'Flatwork'],
    ['id' => '22-1140', 'name' => 'FIMCO Nitrogen & Condenser Pads', 'type' => 'Industrial'],
    ['id' => '22-2000', 'name' => 'Gypsum Creek Crossing Repairs', 'type' => 'OH / Internal'],
    ['id' => '22-2010', 'name' => 'Warrior-Davidson T&M 2022', 'type' => 'Hotel'],
    ['id' => '22-3000', 'name' => 'Vermillion Elementary School', 'type' => 'Schools/Colleges'],
    ['id' => '22-4200', 'name' => 'Floyd Valley Hospital Specialty Clinic', 'type' => 'Healthcare'],
    ['id' => '22-5010', 'name' => 'Lakeport Commons Ross Buildout', 'type' => 'Retail'],
    ['id' => '22-5020', 'name' => 'Wholestone Pork Kill Floor', 'type' => 'Industrial'],
    ['id' => '22-5030', 'name' => 'Dollar General NSC', 'type' => 'Retail'],
    ['id' => '22-5040', 'name' => '38th Street Booster Station', 'type' => 'WWTP'],
    ['id' => '22-5050', 'name' => 'Telco Triad Credit Union', 'type' => 'Retail'],
    ['id' => '22-5060', 'name' => 'Akron-Westfield CSD Renovations', 'type' => 'Schools/Colleges'],
    ['id' => '22-6010', 'name' => 'Wholestone Rendering', 'type' => 'WWTP'],
    ['id' => '22-6011', 'name' => 'Wholestone Paving T&M', 'type' => 'Flatwork'],
    ['id' => '22-6020', 'name' => 'Crete Core Ingredients WWPT', 'type' => 'WWTP'],
    ['id' => '22-6030', 'name' => 'Double Tree Hotel Renovation', 'type' => 'Hotel'],
    ['id' => '22-7010', 'name' => 'Lincoln Way Energy Concrete', 'type' => 'Ag'],
    ['id' => '22-8000', 'name' => 'RJ Tide 2022 Warranty Work', 'type' => 'OH / Internal'],
    ['id' => '23-0010', 'name' => 'Bertrand EWAC 2023', 'type' => 'EWAC'],
    ['id' => '23-0020', 'name' => 'Hodgson EWAC 2023', 'type' => 'EWAC'],
    ['id' => '23-0030', 'name' => 'Schueder EWAC 2023', 'type' => 'EWAC'],
    ['id' => '23-0040', 'name' => 'Billings EWAC 2023', 'type' => 'EWAC'],
    ['id' => '23-0090', 'name' => 'RJ Tide 2023 Capital Improvements', 'type' => 'OH / Internal'],
    ['id' => '23-1310', 'name' => 'Bomgaars 2023 Paving', 'type' => 'Flatwork'],
    ['id' => '23-1320', 'name' => 'Reis Residence', 'type' => 'Flatwork'],
    ['id' => '23-1330', 'name' => 'Holton Chiropractic Clinic Parking Lot', 'type' => 'Flatwork'],
    ['id' => '23-1340', 'name' => 'Remsen St. Mary\'s Floor Grinding', 'type' => 'Schools/Colleges'],
    ['id' => '23-1350', 'name' => 'Catholic Charities Parking Lot Repairs', 'type' => 'Flatwork'],
    ['id' => '23-1360', 'name' => 'Omaha Industries T&M', 'type' => 'Industrial'],
    ['id' => '23-1370', 'name' => 'Eggerling Shop', 'type' => 'Flatwork'],
    ['id' => '23-1380', 'name' => 'Pollman Street Patching', 'type' => 'Flatwork'],
    ['id' => '23-1390', 'name' => 'Mater Dei Misc. Concrete 2023', 'type' => 'Flatwork'],
    ['id' => '23-1400', 'name' => 'Rick Bertrand Shop Paving', 'type' => 'Flatwork'],
    ['id' => '23-1410', 'name' => 'Recobs Paving', 'type' => 'Flatwork'],
    ['id' => '23-1420', 'name' => 'Siouxland Ethanol Receiving Road Paving', 'type' => 'Flatwork'],
    ['id' => '23-1430', 'name' => 'Busch Pole Building Flatwork', 'type' => 'Flatwork'],
    ['id' => '23-1440', 'name' => 'Highway 20 Storm Flume Rebar Installation', 'type' => 'Industrial'],
    ['id' => '23-1450', 'name' => 'Transco Rail CIP Wall', 'type' => 'Industrial'],
    ['id' => '23-1460', 'name' => 'Emerson Water Improvements', 'type' => 'WWTP'],
    ['id' => '23-1470', 'name' => 'FIMCO Washdown Slab', 'type' => 'Flatwork'],
    ['id' => '23-1480', 'name' => 'Royal Canin Equip Leg Grouting', 'type' => 'Industrial'],
    ['id' => '23-2310', 'name' => 'Siouxland Ethanol 2023', 'type' => 'Industrial'],
    ['id' => '23-2320', 'name' => 'Wholestone T&M 2023', 'type' => 'Industrial'],
    ['id' => '23-5300', 'name' => 'Mondamin WTP Upgrades', 'type' => 'WWTP'],
    ['id' => '23-5310', 'name' => ' MAE Neal South Renovations', 'type' => 'Industrial'],
    ['id' => '23-5320', 'name' => 'Hinton Substation', 'type' => 'Industrial'],
    ['id' => '23-5340', 'name' => 'Double Tree Hotel Phase 2', 'type' => 'Hotel'],
    ['id' => '23-5350', 'name' => 'Performance Pet Products', 'type' => 'Industrial'],
    ['id' => '23-5351', 'name' => 'Performance Pet Products GC Direct Work', 'type' => 'Industrial'],
    ['id' => '23-5360', 'name' => 'Lewis & Clark Behavioral Health Center Sitework', 'type' => 'Flatwork'],
    ['id' => '23-5361', 'name' => 'L&C Mech Pads-Redlinger', 'type' => 'Flatwork'],
    ['id' => '23-5362', 'name' => 'L&C Transformer Pad-Thompson', 'type' => 'Flatwork'],
    ['id' => '23-5370', 'name' => 'Sioux City WWTP Ultraviolet Disinfection', 'type' => 'WWTP'],
    ['id' => '23-5371', 'name' => 'COSC WWTP UV Thompson Paving', 'type' => 'WWTP'],
    ['id' => '23-5372', 'name' => 'COSC WWTP UV RP T&M', 'type' => 'WWTP'],
    ['id' => '23-5380', 'name' => 'Clay County Law Enforcement Center', 'type' => 'Institutional'],
    ['id' => '23-5390', 'name' => 'Wayne Early Learning Center & HS Addn', 'type' => 'Schools/Colleges'],
    ['id' => '23-6310', 'name' => 'LDS Church Parking Lot', 'type' => 'Flatwork'],
    ['id' => '23-6320', 'name' => 'Loberg 60-13 Grain Bin Concrete', 'type' => 'Ag'],
    ['id' => '23-6330', 'name' => 'Pilgrim\'s Pride Georgia', 'type' => 'Industrial'],
    ['id' => '23-6340', 'name' => 'Trinity Heights Chapel', 'type' => 'EWAC'],
    ['id' => '23-6350', 'name' => 'Hillcrest Parking Lot', 'type' => 'Flatwork'],
    ['id' => '23-8000', 'name' => 'RJ Tide 2023 Warranty Work', 'type' => 'OH / Internal'],
    ['id' => '24-0005', 'name' => 'STF WWTP Phase 4', 'type' => 'WWTP'],
    ['id' => '24-0015', 'name' => 'Loring Hospital – Clinic Addition & Remodel', 'type' => 'Healthcare'],
    ['id' => '24-0025', 'name' => 'Transco Railway Retaining Wall', 'type' => 'Industrial'],
    ['id' => '24-0035', 'name' => 'Royal Canin T&M 2024', 'type' => 'Industrial'],
    ['id' => '24-0045', 'name' => 'Trinity Electric Paving T&M-Wayne Schools', 'type' => 'Schools/Colleges'],
    ['id' => '24-0055', 'name' => 'Siouxland Ethanol Wetpad Paving', 'type' => 'Flatwork'],
    ['id' => '24-0065', 'name' => 'Crawford County Hospital', 'type' => 'Healthcare'],
    ['id' => '24-0066', 'name' => 'CCMH Concrete Replacement', 'type' => 'Healthcare'],
    ['id' => '24-0075', 'name' => 'Heelan Monument Sign', 'type' => 'Schools/Colleges'],
    ['id' => '24-0085', 'name' => 'Bomgaars Parking Lot 2024', 'type' => 'Flatwork'],
    ['id' => '24-0095', 'name' => 'Dayton Freight CB Paving Repairs', 'type' => 'Flatwork'],
    ['id' => '24-0105', 'name' => 'Hillcrest NE Inlet Repair', 'type' => 'Flatwork'],
    ['id' => '24-0115', 'name' => 'FIMCO Vibration Testing', 'type' => 'Industrial'],
    ['id' => '24-0125', 'name' => 'Smithfield Fence & Turnstile', 'type' => 'Flatwork'],
    ['id' => '24-0135', 'name' => 'St. Michael\'s Church Driveway', 'type' => 'Flatwork'],
    ['id' => '24-0145', 'name' => 'Primghar Sanitary Sewer Repair', 'type' => 'Flatwork'],
    ['id' => '24-0155', 'name' => 'Primghar WWTP Screen Building Paving', 'type' => 'Flatwork'],
    ['id' => '24-0165', 'name' => 'FIMCO Corporate Office Stoops', 'type' => 'Flatwork'],
    ['id' => '24-0175', 'name' => 'STF Paving 2024', 'type' => 'Flatwork'],
    ['id' => '24-0185', 'name' => 'Gelita Paving 2024', 'type' => 'Flatwork'],
    ['id' => '24-7005', 'name' => 'Craig Coop Loadout Concrete', 'type' => 'Ag'],
    ['id' => '24-7015', 'name' => 'JE Meuret Crofton Receiving Concrete', 'type' => 'Ag'],
    ['id' => '24-8001', 'name' => 'Warranty AG-2320 LWE Bin Sweep', 'type' => 'Warranty'],
    ['id' => '24-8002', 'name' => 'Warranty 20-6051 Wholestone SnapChill', 'type' => 'Warranty'],
    ['id' => '24-8003', 'name' => 'Warranty 23-6330 Pilgrims Pride', 'type' => 'Warranty'],
    ['id' => '24-8004', 'name' => 'Warranty 22-5060 Akron CSD', 'type' => 'Warranty'],
    ['id' => '24-9005', 'name' => 'Bertrand EWAC 2024', 'type' => 'EWAC'],
    ['id' => '24-9010', 'name' => 'Schueder EWAC 2024', 'type' => 'EWAC'],
    ['id' => '24-9015', 'name' => 'Hodgson EWAC 2024', 'type' => 'EWAC'],
    ['id' => '24-9025', 'name' => 'Jimenez EWAC 2024', 'type' => 'EWAC'],
    ['id' => '24-9035', 'name' => 'Irwin EWAC 2024', 'type' => 'EWAC'],
    ['id' => '24-9800', 'name' => 'Gypsum Creek Crossing 2024', 'type' => 'OH / Internal'],
    ['id' => '25-0010', 'name' => 'Mater Dei Parish 2025 Charity Work', 'type' => 'Institutional'],
    ['id' => '25-0020', 'name' => 'St. Joe Rail Scale Approaches', 'type' => 'Industrial'],
    ['id' => '25-0030', 'name' => 'Jebro Tank Pad Sioux City', 'type' => 'Industrial'],
    ['id' => '25-0040', 'name' => 'Perdue Farms Grouting', 'type' => 'WWTP'],
    ['id' => '25-0050', 'name' => 'High Plains Processing Flatwork Building', 'type' => 'Industrial'],
    ['id' => '25-0051', 'name' => 'High Plains Processing Flatwork Site', 'type' => 'Industrial'],
    ['id' => '25-0052', 'name' => 'High Plains Processing Flatwork Insurance', 'type' => 'Industrial'],
    ['id' => '25-0060', 'name' => 'STF Cut Floor Slab Replacements', 'type' => 'Industrial'],
    ['id' => '25-0070', 'name' => 'Trinity Heights Courtyard / Fountain', 'type' => 'Institutional'],
    ['id' => '25-0080', 'name' => 'Trinity Heights Amphitheater', 'type' => 'Flatwork'],
    ['id' => '25-0090', 'name' => 'Trinity Heights Chapel Engraving', 'type' => 'Decorative'],
    ['id' => '25-0100', 'name' => 'Royal Canin WWTP', 'type' => 'WWTP'],
    ['id' => '25-0110', 'name' => 'Gelita P100 Pork Tower', 'type' => 'Industrial'],
    ['id' => '25-0120', 'name' => 'Cherokee RWS 2024 System Improvements', 'type' => 'WWTP'],
    ['id' => '25-0130', 'name' => 'Okoboji Elementary School', 'type' => 'Schools/Colleges'],
    ['id' => '25-0140', 'name' => 'Heelan 2025 Parking Lot', 'type' => 'Flatwork'],
    ['id' => '25-0150', 'name' => 'A&A Underground Sgt Bluff T&M', 'type' => 'Flatwork'],
    ['id' => '25-0160', 'name' => 'Bomgaars Paving 2025', 'type' => 'Flatwork'],
    ['id' => '25-0170', 'name' => 'Opportunities Unlimited Parking Lot', 'type' => 'Flatwork'],
    ['id' => '25-0180', 'name' => 'South Sioux City WWTF', 'type' => 'WWTP'],
    ['id' => '25-0190', 'name' => 'Prime Living Apartments Slab Replacement T&M', 'type' => 'Institutional'],
    ['id' => '25-0200', 'name' => 'JBS Grand Island Tank Grouting', 'type' => 'WWTP'],
    ['id' => '25-0201', 'name' => 'JBS Grand Island Tank Grout Remove & Replace', 'type' => 'WWTP'],
    ['id' => '25-0210', 'name' => 'STF Rendering Paving-Grease Loudout-Headwall', 'type' => 'Flatwork'],
    ['id' => '25-0220', 'name' => 'FIMCO Equipment Foundations 2025', 'type' => 'Industrial'],
    ['id' => '25-0230', 'name' => '38th Street Booster Station Grouting', 'type' => 'Industrial'],
    ['id' => '25-0240', 'name' => 'Gelita Sludge Storage Paving', 'type' => 'Industrial'],
    ['id' => '25-0250', 'name' => 'Primghar WWTP Paving 2025', 'type' => 'Flatwork'],
    ['id' => '25-7010', 'name' => 'Siouxland Ethanol Scales Concrete', 'type' => 'Ag'],
    ['id' => '25-7020', 'name' => 'Remsen Coop Cattle Feed Mill Concrete', 'type' => 'OH / Internal'],
    ['id' => '25-7030', 'name' => 'CVA Hinton Loading Dock Concrete', 'type' => 'OH / Internal'],
    ['id' => '25-8005', 'name' => 'Warranty AG-24005 Craig Feed Mill Loadout', 'type' => 'Warranty'],
    ['id' => '25-8015', 'name' => 'Warranty - 23-5350 Performance Pet Insulation Costs', 'type' => 'Warranty'],
    ['id' => '25-9005', 'name' => 'Bertrand EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9015', 'name' => 'Jimenez EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9025', 'name' => 'Schueder EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9035', 'name' => 'Hodgson EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9045', 'name' => 'Urbanec EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9055', 'name' => 'Billings EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9065', 'name' => 'Hoffman EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9075', 'name' => 'Schmidt EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9085', 'name' => 'Greinke EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9095', 'name' => 'Anderson EWAC 2025', 'type' => 'EWAC'],
    ['id' => '25-9800', 'name' => 'Gypsum Creek Crossing 2025', 'type' => 'OH / Internal'],
    ['id' => '25-9999', 'name' => '2025 RJT Office Capital Improvements', 'type' => 'OH / Internal'],
    ['id' => '26-0005', 'name' => 'Sgt Bluff Eye Care SOG', 'type' => 'Flatwork'],
    ['id' => '26-0015', 'name' => 'Heelan Walk of Faith', 'type' => 'Schools/Colleges'],
    ['id' => '26-0025', 'name' => 'Heelan-Cathedral Parking Lot', 'type' => 'Schools/Colleges'],
    ['id' => '26-0035', 'name' => 'Blessed Sacrament Entry Stairs', 'type' => 'Decorative'],
    ['id' => '26-0045', 'name' => 'Gelita Fire Well Pump House & Tank Foundation', 'type' => 'Industrial'],
    ['id' => '26-0055', 'name' => 'Sunnybrook Church Demo - Charity', 'type' => 'OH / Internal'],
    ['id' => '26-0065', 'name' => 'STF Rendering Fourth Silo Pad', 'type' => 'Industrial'],
    ['id' => '26-0075', 'name' => 'Carroll Hospital Parking Garage & Paving', 'type' => 'Healthcare'],
    ['id' => '26-0085', 'name' => 'St. Anthony Hospital Emergency Dept', 'type' => 'Healthcare'],
    ['id' => '26-0095', 'name' => 'Immaculate Conception 2026 Sidewalk Repair', 'type' => 'Flatwork'],
    ['id' => '26-0105', 'name' => 'Darling WWPT Wahoo NE', 'type' => 'WWTP'],
    ['id' => '26-0115', 'name' => 'Clay Rural Water Systems', 'type' => 'WWTP'],
    ['id' => '26-0125', 'name' => 'Immaculate Conception Front Courtyard', 'type' => 'Flatwork'],
    ['id' => '26-0135', 'name' => 'Fareway 2026 Concrete Maintenance', 'type' => 'Flatwork'],
    ['id' => '26-0145', 'name' => 'STF Pet Food Pourback', 'type' => 'Industrial'],
    ['id' => '26-0155', 'name' => 'Heelan 2026 Parking Lot Repairs', 'type' => 'Flatwork'],
    ['id' => '26-0165', 'name' => 'Projects for Patriots-4335 Correctionville Road', 'type' => 'OH / Internal'],
    ['id' => '26-0175', 'name' => 'Rick Bertrand Mini Golf Course', 'type' => ''],
    ['id' => '26-0185', 'name' => 'STF Emergency Pumping & Manhole Repairs', 'type' => 'WWTP'],
    ['id' => '26-7005', 'name' => 'Siouxland Ethanol Rail Scale Concrete', 'type' => 'Ag'],
    ['id' => '26-7015', 'name' => 'CVA Hinton Robot Equipment Pad', 'type' => 'Flatwork'],
    ['id' => '26-9005', 'name' => 'Bertrand EWAC 2026', 'type' => 'EWAC'],
    ['id' => '26-9010', 'name' => 'Urbanec EWAC 2026', 'type' => 'EWAC'],
    ['id' => '26-9020', 'name' => 'Billings EWAC 2026', 'type' => 'EWAC'],
    ['id' => '26-9030', 'name' => 'Lutter EWAC 2026', 'type' => 'EWAC'],
    ['id' => '26-9040', 'name' => 'Schueder EWAC 2026', 'type' => 'EWAC'],
    ['id' => '26-9050', 'name' => 'Greinke EWAC 2026', 'type' => 'EWAC'],
    ['id' => '26-9060', 'name' => 'Hodgson EWAC 2026', 'type' => 'EWAC'],
    ['id' => '26-9070', 'name' => 'Jimenez EWAC 2026', 'type' => 'EWAC'],
    ['id' => '26-9800', 'name' => 'Gypsum Creek Crossing 2026', 'type' => 'OH / Internal'],
    ['id' => '26-9999', 'name' => '2026 RJT Office Capital Improvements', 'type' => 'OH / Internal'],
    ['id' => 'AG-2115', 'name' => 'AgFirst Toronto 90\' Bin Sweep', 'type' => 'Ag'],
    ['id' => 'AG-2205', 'name' => 'Lincoln Way Energy Bin Project PreCon', 'type' => 'Ag'],
    ['id' => 'AG-2215', 'name' => 'AgFirst Grain Storage PreCon', 'type' => 'Ag'],
    ['id' => 'AG-2230', 'name' => 'Lincolnway Energy 40k Upgrade', 'type' => 'Ag'],
    ['id' => 'AG-2305', 'name' => 'Loberg 60-13 Grain Bin Addition', 'type' => 'Ag'],
    ['id' => 'AG-2310', 'name' => 'Custom Feed Services 2023', 'type' => 'Ag'],
    ['id' => 'AG-2315', 'name' => 'Country Partners 2023 - Ewing,NE', 'type' => 'Ag'],
    ['id' => 'AG-2320', 'name' => 'LincolnWay Energy Bin Sweep-Springland', 'type' => 'Ag'],
    ['id' => 'AG-2330', 'name' => 'Lemars AgriCenter Accessibility & Cracker Spouting', 'type' => 'Ag'],
    ['id' => 'AG-2340', 'name' => 'Craig Coop Loadout Bin Site Design', 'type' => 'Ag'],
    ['id' => 'AG-24005', 'name' => 'Craig Feed Mill Loadout Addition', 'type' => 'Ag'],
    ['id' => 'AG-24010', 'name' => 'AgState PreCon-10k Transfer Conveyor', 'type' => 'Ag'],
    ['id' => 'AG-24020', 'name' => 'JE Meuret Crofton South Receiving', 'type' => 'Ag'],
    ['id' => 'AG-24030', 'name' => 'Michael Foods Bin Hopper Repair', 'type' => 'Ag'],
    ['id' => 'AG-24040', 'name' => 'Loberg Headgate & Return Cups', 'type' => 'Ag'],
    ['id' => 'AG-24050', 'name' => 'Whole Grains T&M Repairs Dakota City', 'type' => 'Ag'],
    ['id' => 'AG-24060', 'name' => 'Sandhills Renewable Energy Shutdown Repairs', 'type' => 'Ag'],
    ['id' => 'AG-24070', 'name' => 'Siouxland Ethanol Scales Precon', 'type' => 'Ag'],
    ['id' => 'AG-24080', 'name' => 'Farmers Feed Boyden Plugged Mixer Leg', 'type' => 'Ag'],
    ['id' => 'AG-24090', 'name' => 'Michael Foods Feed Mill Structural Review', 'type' => 'Ag'],
    ['id' => 'AG-24100', 'name' => 'AgState Kingsley Door Concrete Repair', 'type' => 'Ag'],
    ['id' => 'AG-24110', 'name' => 'Premium Feed Head Gates T&M', 'type' => 'Ag'],
    ['id' => 'AG-24120', 'name' => 'Didion Ethanol Emergency Damper Removal', 'type' => 'Ag'],
    ['id' => 'AG-24130', 'name' => 'Farmers Coop Lindsay Sweep Advance Drive', 'type' => 'Ag'],
    ['id' => 'AG-24140', 'name' => 'Craig Dumpster Pad', 'type' => 'Ag'],
    ['id' => 'AG-24150', 'name' => 'Whole Grains Reclaim Drag N-S Motor Replacement', 'type' => 'Ag'],
    ['id' => 'AG-24160', 'name' => 'Craig Coop Microsystem Transition', 'type' => 'Ag'],
    ['id' => 'AG-24170', 'name' => 'Whole Grains Top Belt T&M', 'type' => 'Ag'],
    ['id' => 'AG-24180', 'name' => 'Farmers Coop Lindsay Sweep Auger Repair', 'type' => 'Ag'],
    ['id' => 'AG-24190', 'name' => 'Whole Grains Gate Repair', 'type' => 'Ag'],
    ['id' => 'AG-24200', 'name' => 'Whole Grains Leg Bearing Replacement', 'type' => 'Ag'],
    ['id' => 'AG-24210', 'name' => 'Le Mars Agri-Center Wood House Repairs', 'type' => 'Ag'],
    ['id' => 'AG-24220', 'name' => 'Whole Grains Top Belt Tripper Bearing', 'type' => 'Ag'],
    ['id' => 'AG-24230', 'name' => 'Whole Grains Bottom Belt Tail Bearing', 'type' => 'Ag'],
    ['id' => 'AG-24240', 'name' => 'Sandhills Renewable Energy Fall-2024 Shutdown', 'type' => 'Ag'],
    ['id' => 'AG-24250', 'name' => 'Siouxland Ethanol Scales', 'type' => 'Ag'],
    ['id' => 'AG-24260', 'name' => 'Whole Grains Crush Plant PreCon', 'type' => 'Ag'],
    ['id' => 'AG-24270', 'name' => 'Whole Grains Dust System T&M', 'type' => 'Ag'],
    ['id' => 'AG-24280', 'name' => 'Whole Grains Dryer Motor Replacement', 'type' => 'Ag'],
    ['id' => 'AG-24290', 'name' => 'Whole Grains East Main Leg Motor and Drive', 'type' => 'Ag'],
    ['id' => 'AG-24300', 'name' => 'Michael Foods Bin Air Floor Repairs', 'type' => 'Ag'],
    ['id' => 'AG-24310', 'name' => 'Whole Grains Top Belt T&M', 'type' => 'Ag'],
    ['id' => 'AG-24320', 'name' => 'Whole Grains Weigh Garner Inspection T&M', 'type' => 'Ag'],
    ['id' => 'AG-24330', 'name' => 'Whole Grains North to South Reclaim Belt T&M', 'type' => 'Ag'],
    ['id' => 'AG-24340', 'name' => 'Remsen Farmers Coop Steel Building Repair', 'type' => 'Ag'],
    ['id' => 'AG-24350', 'name' => 'SRE BE-215 Receiving Leg Head Shaft Replacement', 'type' => 'Ag'],
    ['id' => 'AG-25005', 'name' => 'Whole Grains Annex Reclaim Belt T&M', 'type' => 'Ag'],
    ['id' => 'AG-25015', 'name' => 'LincolnWay Energy Belt Repairs', 'type' => 'Ag'],
    ['id' => 'AG-25025', 'name' => 'Custom Feeds Head Bearings', 'type' => 'Ag'],
    ['id' => 'AG-25035', 'name' => 'Timmerman Loadout Bin Roof & Spouting', 'type' => 'Ag'],
    ['id' => 'AG-25045', 'name' => 'Whole Grain Splice N-S Belt', 'type' => 'Ag'],
    ['id' => 'AG-25055', 'name' => 'Remsen Coop Cattle Feed Mill', 'type' => 'Ag'],
    ['id' => 'AG-25065', 'name' => 'Siouxland Ethanol DDG Bldg FIll Drag', 'type' => 'Ag'],
    ['id' => 'AG-25075', 'name' => 'LincolnWay Energy May-2025 Shutdown', 'type' => 'Ag'],
    ['id' => 'AG-25085', 'name' => 'Whole Grain N-S Reclaim Conveyor Tracking', 'type' => 'Ag'],
    ['id' => 'AG-25095', 'name' => 'Craig Coop Truck in Sky Vibrators', 'type' => 'Ag'],
    ['id' => 'AG-25105', 'name' => 'Whole Grain N-S Reclaim Belt Re-Splicing', 'type' => 'Ag'],
    ['id' => 'AG-25115', 'name' => 'Siouxland Ethanol Poly Tank Leveling', 'type' => 'Ag'],
    ['id' => 'AG-25125', 'name' => 'PigCents Tote System', 'type' => 'Ag'],
    ['id' => 'AG-25135', 'name' => 'Plymouth Energy Receiving Spout Upgrades', 'type' => 'Ag'],
    ['id' => 'AG-25145', 'name' => 'Plymouth Energy Receiving Drag Repairs', 'type' => 'Ag'],
    ['id' => 'AG-25155', 'name' => 'Plymouth Energy Scalper Spout Replacement', 'type' => 'Ag'],
    ['id' => 'AG-25165', 'name' => 'Remsen Coop Flex System', 'type' => 'Ag'],
    ['id' => 'AG-25175', 'name' => 'Timmerman Loadout Painting', 'type' => 'Ag'],
    ['id' => 'AG-25185', 'name' => 'Whole Grains Upper Fill Belt Re-Splice', 'type' => 'Ag'],
    ['id' => 'AG-25195', 'name' => 'Whole Grains Leg Belt Replacement', 'type' => 'Ag'],
    ['id' => 'AG-25205', 'name' => 'CVA Oyens Feed Mill Distributor', 'type' => 'Ag'],
    ['id' => 'AG-25215', 'name' => 'CVA Laurel Gate Repairs', 'type' => 'Ag'],
    ['id' => 'AG-25225', 'name' => 'Whole Grains Dryer Fan Motor Sept 2025', 'type' => 'Ag'],
    ['id' => 'AG-25235', 'name' => 'CVA Bow Valley Loadout Spouting System', 'type' => 'Ag'],
    ['id' => 'AG-25245', 'name' => 'Timmerman Bucket Elevator Repair', 'type' => 'Ag'],
    ['id' => 'AG-25255', 'name' => 'Siouxland Ethanol G3 Rail Scale Approaches Design', 'type' => 'Ag'],
    ['id' => 'AG-25265', 'name' => 'CVA Oyens Bean Flat Conveyor Drag Chain', 'type' => 'Ag'],
    ['id' => 'AG-25275', 'name' => 'Timmerman Leg Belt Replacement', 'type' => 'Ag'],
    ['id' => 'AG-25285', 'name' => 'Yaggie\'s Preharvest T&M', 'type' => 'Ag'],
    ['id' => 'AG-25295', 'name' => 'CVA Oyens Feed Mill Corn Spout', 'type' => 'Ag'],
    ['id' => 'AG-25305', 'name' => 'CVA Laurel Line Dryer Discharge Spout', 'type' => 'Ag'],
    ['id' => 'AG-25315', 'name' => 'Craig Coop Feed Mill Upgrade Design', 'type' => 'Ag'],
    ['id' => 'AG-25320', 'name' => 'Craig Coop 2025 Misc. Parts Invoicing', 'type' => 'Ag'],
    ['id' => 'AG-25325', 'name' => 'CVA Laurel Safety Improvements T&M', 'type' => 'Ag'],
    ['id' => 'AG-25335', 'name' => 'CVA Laurel Access Platforms', 'type' => 'Ag'],
    ['id' => 'AG-25345', 'name' => 'CVA Laurel Silo Door Repairs', 'type' => 'Ag'],
    ['id' => 'AG-25355', 'name' => 'CVA Oyens Feed Mill Corn Leg Gearbox Replacement', 'type' => 'Ag'],
    ['id' => 'AG-25365', 'name' => 'Farmers Feed Roof Pick Points & Leg Align', 'type' => 'Ag'],
    ['id' => 'AG-25375', 'name' => 'Gelita Millwright T&M-RP', 'type' => 'Industrial'],
    ['id' => 'AG-25385', 'name' => 'CVA Wakefield Wet Bin Fans', 'type' => 'Ag'],
    ['id' => 'AG-25395', 'name' => 'CVA Laurel Dust System Repair', 'type' => 'Ag'],
    ['id' => 'AG-25405', 'name' => 'Whole Grain Splice Top Belt', 'type' => 'Ag'],
    ['id' => 'AG-25415', 'name' => 'CVA Hinton Bucket Elevator', 'type' => 'Ag'],
    ['id' => 'AG-25425', 'name' => 'CVA Wakefield Stacker Splice', 'type' => 'Ag'],
    ['id' => 'AG-25435', 'name' => 'CVA Oyens Corn Scalper Upgrades', 'type' => 'Ag'],
    ['id' => 'AG-25445', 'name' => 'CVA Oyens Corn Flat Bldg Exhaust Fan', 'type' => 'Ag'],
    ['id' => 'AG-25455', 'name' => 'CVA Oyens Roller Mill Modifications', 'type' => 'Ag'],
    ['id' => 'AG-25465', 'name' => 'Remsen Coop Feed Mill Micro Sys Scale Drum', 'type' => 'Ag'],
    ['id' => 'AG-25475', 'name' => 'Le Mars Agri-Center South Bean Bin Access Hatch', 'type' => 'Ag'],
    ['id' => 'AG-25485', 'name' => 'Craig Cattle Grinder Leg Drive & Bearings', 'type' => 'Ag'],
    ['id' => 'AG-25495', 'name' => 'CVA Oyens Mixer Leg Inlet Upgrade', 'type' => 'Ag'],
    ['id' => 'AG-25505', 'name' => 'LincolnWay Energy Emergency Conveyor Belt Repair', 'type' => 'Ag'],
    ['id' => 'AG-25515', 'name' => 'CVA Oyens Feed Mill Leg Tracking', 'type' => 'Ag'],
    ['id' => 'AG-25805', 'name' => 'CVA Hinton Mill Improvements & Loading Dock', 'type' => 'Ag'],
    ['id' => 'AG-25815', 'name' => 'Craig Coop Feed Mill Ingredient Bin Improvements', 'type' => 'Ag'],
    ['id' => 'AG-26005', 'name' => 'CVA Wakefield Loadout Spout', 'type' => 'Ag'],
    ['id' => 'AG-26015', 'name' => 'CVA Wakefield Line Loadout Bin Fill Spouts', 'type' => 'Ag'],
    ['id' => 'AG-26020', 'name' => 'Pigcents 2026 Material', 'type' => 'Ag'],
    ['id' => 'AG-26030', 'name' => 'FIMCO Mezzanine', 'type' => 'Industrial'],
    ['id' => 'AG-26040', 'name' => 'Craig Coop Major Scale Upgrade', 'type' => 'Ag'],
    ['id' => 'AG-26050', 'name' => 'Remsen Feed Mill Loadout Gate T&M', 'type' => 'Ag'],
    ['id' => 'AG-26060', 'name' => 'Remsen Feed Mill Receiving Drag Chain', 'type' => 'Ag'],
    ['id' => 'AG-26070', 'name' => 'CVA Bloomfield Fertilizer Belt', 'type' => 'Ag'],
    ['id' => 'AG-26080', 'name' => 'Sandhills Renewable Energy Reclaim Speed Up', 'type' => 'Ag'],
    ['id' => 'AG-26090', 'name' => 'CVA Hinton Warehouse Forklift Stop', 'type' => 'Ag'],
    ['id' => 'AG-26100', 'name' => 'Dixon Elevator Spouting', 'type' => 'Ag'],
    ['id' => 'AG-26110', 'name' => 'Rockdale TX Pipefitting', 'type' => 'Industrial'],
    ['id' => 'AG-26120', 'name' => 'CVA Duncan Safety Guarding', 'type' => 'Ag'],
    ['id' => 'AG-26130', 'name' => 'CVA Elgin Grain Facility Safety Guarding', 'type' => 'Ag'],
    ['id' => 'AG-26140', 'name' => 'CVA Petersburg Grain Bin Handrails', 'type' => 'Ag'],
    ['id' => 'AG-26150', 'name' => 'CVA Elgin Feed Mill Safety Guarding', 'type' => 'Ag'],
    ['id' => 'AG-26160', 'name' => 'Wylie TX WWTP Emergency Shoring T&M', 'type' => 'Ag'],
    ['id' => 'AG-26170', 'name' => 'RP Gelita P100 T&M', 'type' => 'Ag'],
    ['id' => 'AG-26180', 'name' => 'LWE May-2026 Shutdown Inspections', 'type' => 'Ag'],
    ['id' => 'AG-26190', 'name' => 'CVA Bow Valley T&M Guarding', 'type' => 'Ag'],
    ['id' => 'AG-26200', 'name' => 'CVA Hinton Feed Mill Equipment Guarding', 'type' => 'Ag'],
    ['id' => 'AG-26210', 'name' => 'CVA Bow Valley Receiving Leg Repairs', 'type' => 'Ag'],
    ['id' => 'AG-26220', 'name' => 'CVA Duncan Leg Tracking & Hazmon', 'type' => 'Ag'],
    ['id' => 'AG-26230', 'name' => 'CVA Oyens Whole Corn Leg Gearbox Replacement', 'type' => 'Ag'],
    ['id' => 'AG-26240', 'name' => 'CVA Hinton Feed Mill Receiving Spout Upgrades', 'type' => 'Ag'],
    ['id' => 'AG-26250', 'name' => 'Sandhills Renewable Energy Leg Buckets', 'type' => 'Ag'],
    ['id' => 'AG-26260', 'name' => 'Plymouth Energy West Truck Receiving Drag', 'type' => 'Ag'],
    ['id' => 'AG-26270', 'name' => 'Plymouth Energy Receiving Bin Fill Drag', 'type' => 'Ag'],
    ['id' => 'AG-26280', 'name' => 'Plymouth Energy Transition to West Bin', 'type' => 'Ag'],
    ['id' => 'AG-26290', 'name' => 'Plymouth Energy Shutdown Leg Belts', 'type' => 'Ag'],
    ['id' => 'AG-26300', 'name' => 'Plymouth Energy Discharge Transitions & Leg Rework', 'type' => 'Ag'],
    ['id' => 'AG-26310', 'name' => 'Plymouth Energy East Receiving Leg Bonnet', 'type' => 'Ag'],
    ['id' => 'AG-26320', 'name' => 'Craig Coop Hoppers Warranty', 'type' => 'Ag'],
    ['id' => 'AG-26330', 'name' => 'Plymouth Energy Dust Reclaim System', 'type' => 'Ag'],
    ['id' => 'AG-26340', 'name' => 'Bromm Cattle Unload Auger & Leg Service', 'type' => 'Ag'],
    ['id' => 'AG-26350', 'name' => 'SRE Shorten BE-310 Leg Belt', 'type' => 'Ag'],
    ['id' => 'AG-26360', 'name' => 'CVA Duncan T&M Guarding', 'type' => 'Ag'],
    ['id' => 'AG-26370', 'name' => 'CVA Hinton Feed Mill T&M Repairs', 'type' => 'Ag'],
    ['id' => 'AG-26380', 'name' => 'CVA Oyens Salt Bin Gearbox', 'type' => 'Ag'],
    ['id' => 'AG-26390', 'name' => 'CVA Wakefield Distributor Repair', 'type' => 'Ag'],
    ['id' => 'AG-26400', 'name' => 'CVA Bow Valley Unload Auger', 'type' => 'Ag'],
    ['id' => 'AG-26410', 'name' => 'Timmerman Leg Repairs', 'type' => 'Ag'],
    ['id' => 'AG-26420', 'name' => 'Farmers Pride Avon West Elevator Upgrades', 'type' => 'Ag'],
    ['id' => 'AG-26430', 'name' => 'Craig Coop GSI 3 Reclaim Repairs-CANCELLED', 'type' => 'Ag'],
    ['id' => 'AG-26440', 'name' => 'CVA Ainsworth Feed Mill Guarding', 'type' => 'Ag'],
    ['id' => 'AG-26450', 'name' => 'CVA Elgin Grain Receiving Leg Upgrades', 'type' => 'Ag'],
    ['id' => 'AG-26810', 'name' => 'Siouxland Ethanol Rail Scale Approaches', 'type' => 'Ag'],
    ['id' => 'AG-26820', 'name' => 'Craig Coop Mixer Leg', 'type' => 'Ag'],
    ['id' => 'AG-26910', 'name' => 'Knobbe Receiving Complex Precon', 'type' => 'Ag'],
    ['id' => 'AGS230001', 'name' => 'Royal Canin T&M', 'type' => 'Ag'],
    ['id' => 'AGS230002', 'name' => 'Michael Foods Bin Repair', 'type' => 'Ag'],
    ['id' => 'AGS230003', 'name' => 'Oakdale NE Country Partners Access Catwalk', 'type' => 'Ag'],
    ['id' => 'AGS230004', 'name' => 'Spalding NE Country Partners Install Sweeps', 'type' => 'Ag'],
    ['id' => 'AGS230005', 'name' => 'Michael Foods Square Bin Repair', 'type' => 'Ag'],
    ['id' => 'AGS230006', 'name' => 'B&D Hansen Farms Roof Vent Replacement', 'type' => 'Ag'],
    ['id' => 'OH', 'name' => 'Overhead Project', 'type' => 'OH / Internal'],
];
